language: cpp

sudo: false

compiler:
  - gcc

env:
  matrix:
    - COMPILER=g++-4.8 CCOMPILER=gcc-4.8 PUSH_COVERAGE=ON

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - boost-latest
    packages:
      - g++-4.8
      - libboost-all-dev
      - python-pip
    packages:
        - cmake
        - time

before_script:
  - export CXX=$COMPILER CC=$CCOMPILER
  - mkdir build
  - cd build
  - cmake --version
  - cmake ..

script: make
